name: Python CI

on:
  push:
    branches: [ "main" ]

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Lay code tu GitHub
        uses: actions/checkout@v4

      - name: Cai Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Chay file Python
        run: python app.py