name: Python CI CD Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Lay code
        uses: actions/checkout@v4

      - name: Cai Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cai thu vien
        run: pip install -r requirements.txt

      - name: Chay test
        run: pytest

  build-docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Lay code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t hoc-git-python:latest .

      - name: Chay Docker container
        run: docker run hoc-git-python:latest